### ISSUE TITLE
Seperating Racial Categories

### ISSUE THREAD

**Issue by matthew-guerra** [matthew-guerra/master-project#3]
@AaronGullickson 
Should I separate Alaskan Natives from the AIAN category? I can do it but I am afraid that the sample size might be too small

**Comment by matthew-guerra** [comment]
I just saw in RaceD that there is a category for Asian and AIAN, White and AIAN, etc, which I'm guessing will be important for later

**Comment by AaronGullickson** [comment]
@matthew-guerra You will not have a big enough sample size to separate Alaskan Natives.
