### ISSUE TITLE
Unable to render into pdf

### ISSUE THREAD

**Issue by matthew-guerra** [matthew-guerra/master-project#8]
I keep getting an error message about Tinytex not being updated enough to render the document correctly. I have tried updating tinytex myself but that hasn't helped at all. Unsure what to do
@AaronGullickson

**Comment by matthew-guerra** [comment]
tried to figure out the issue and found this:
Your TexLive version is not updated enough to connect to the remote repository and download packages. Please update your installation of TexLive or TinyTex.

When this happens, you can use Quarto update tinytex to download and install an updated version of tinytex.

However doesn't seem to work for me, I get a directory error

**Comment by AaronGullickson** [comment]
@matthew-guerra Once a year, you have to update tinytex for updates to the underlying TexLive distribution. The way to do this is to use the terminal tab in RStudio (not console) to get the command line interface. Then type:

```
quarto update tinytex
```

Let me know if that doesn't work.

**Comment by matthew-guerra** [comment]
Yeah I tried that but it didn't work

**Comment by AaronGullickson** [comment]
I see the problem and its my fault. More specifically, my extension for the PDF document stopped working with some underlying changes to quarto. However, I updated the extension awhile ago to fix that so it just needed to get updated. I went ahead and did that (with `quarto update extension AaronGullickson/aog-article-quarto`) and it renders fine for me. I committed the changes, so if you pull them down, you should be able to render the PDF.
